name: Accessibility Check

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Website URL'
        required: true
        default: 'https://example.com'

jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      - name: Run Python Script
        run: |
          python accessibility.py ${{ github.event.inputs.url }}
